var jsonData = {
	language: "fr",
	title: "ETHNO FRANCE 2023",
	students: [
		{
			firstName: "AFONSO",
			familyName: "ALBUQUERQUE ",
			photoPath: "images/afonso albuquerque.jpg",
			country: "Portugal",
			countryCode: "PT",
			mainInstrument: "guitare et cavaquinho ",
			otherInstruments: "",
			instrumentText: "La guitare est un instrument magnifiquement ingrat. Très pratique à avoir sous la main à tout moment et aussi très beau pour apprendre à \"transcrire\" d'autres instruments.",
			presentationText: "Je suis originaire de Lisbonne, au Portugal. J'ai appris à aimer et à apprécier le pouvoir héréditaire de la musique traditionnelle. D'où qu'elle vienne. ",
			linkDescription: "Recuerdos de Ypacaraí",
			linkURL: "https://www.youtube.com/embed/kdL1aP6f0qE"
		},
		{
			firstName: "CAMILLE",
			familyName: "SINI",
			photoPath: "images/camille sini.jpg",
			country: "France",
			countryCode: "FR",
			mainInstrument: "flûte traversière",
			otherInstruments: "piano",
			instrumentText: "\"Tout le printemps des paysages et des rivières monte comme un encens dans mon coeur, et le souffle de toutes choses chante en mes pensées comme une flûte.\" Rabindranath Tagore",
			presentationText: "Je suis française, mais j'ai des origines italiennes et allemandes. Alors, j'ai toujours été habituée au mélange des cultures et des langues. Je n’imagine simplement pas vivre autrement !",
			linkDescription: "Sofrito - Mongo Santamaria",
			linkURL: "https://www.youtube.com/embed/n__CQt-Xykc"
		},
		{
			firstName: "CAN GÜNEY",
			familyName: "AKSAKALLI",
			photoPath: "images/can guney aksakalli.jpg",
			country: "Turkey",
			countryCode: "TR",
			mainInstrument: "guitare basse",
			otherInstruments: "sax, zurna",
			instrumentText: "J'aime la basse car elle fait le lien entre la percussion et l'harmonie. Elle accompagne les autres instruments et fait danser les gens.",
			presentationText: "Je suis originaire du sud de la Turquie et je vis maintenant à Berlin. J'aime la diversité de cette ville où l'on explore de nombreuses langues, musiques et cultures différentes. J'ai grandi avec la musique folklorique turque.",
			linkDescription: "Can Güney Aksakalli et sa basse",
			linkURL: "https://www.instagram.com/p/CXWkvfYDeXI/"
		},
		{
			firstName: "CLAIRE",
			familyName: "HIEGEL",
			photoPath: "images/claire hiegel.jpg",
			country: "France",
			countryCode: "FR",
			mainInstrument: "voix et daf",
			otherInstruments: "guitare, ukulélé",
			instrumentText: "La Voix m'a permis de grandir, et de me relier à mon corps. Elle est le reflet de ce qui bouillonne en moi, et je souhaite l'offrir au Monde, avec amour et présence.",
			presentationText: "Je suis née à Strasbourg, et me sens de plus en plus curieuse de la culture musicale française. J'ai pu découvrir les musiques des balkans, et me rapprocher de mes origines slovènes, ",
			linkDescription: "Claire Hiegel - Erev shel shoshanim",
			linkURL: "https://www.instagram.com/p/Ccib5GoKi63/embed"
		},
		{
			firstName: "DANIELE",
			familyName: "TORRISI",
			photoPath: "images/daniele torrisi.jpg",
			country: "Italy",
			countryCode: "IT",
			mainInstrument: "guitare accoustique",
			otherInstruments: "bouzouki, ukulele, banjo, mandolin, piano",
			instrumentText: "J'ai besoin de jouer au moins 15 minutes tous les jours, sinon j'ai l'impression qu'il manque quelque chose et je commence à m'énerver.",
			presentationText: "Je suis originaire de Sicile ! J'aime jouer des trucs joyeux pour que les gens s'amusent (moi y compris). Je n'aime pas vraiment apprendre des airs note par note, je préfère surtout improviser.",
			linkDescription: "Bossa Dorado (Instrumental) Rosenberg Trio",
			linkURL: "https://www.youtube.com/embed/bDXIsGfWRTU"
		},
		{
			firstName: "DAVE",
			familyName: "GRAY",
			photoPath: "images/dave grey.jpg",
			country: "United Kingdom",
			countryCode: "GB",
			mainInstrument: "accordéon diatonique",
			otherInstruments: "",
			instrumentText: "",
			presentationText: "J'ai grandi dans le Lincolnshire et je vis à Newcastle upon Tyne. J'ai étudié la musique folklorique et traditionnelle à l'université de Newcastle, où ma technique s'est épanouie sous la direction d'Andy Cutting et de Julian Sutton. Je suis maintenant éducateur et je travaille pour le programme Folkworks à Sage Gateshead. J’apprends aussi la musique traditionnelle à plein de jeunes et d’adultes dans tout le nord de l'Angleterre. J’ai aussi participé à plein d’Ethnos. Enfin, je suis aussi régulièrement en tournée avec Katie Doherty & the Navigators et Världens Band. Je suppose que je suis bien connu pour mon enthousiasme et ma présence sur scène :)",
			linkDescription: "Washington Square Park - The Good Tune",
			linkURL: "https://www.youtube.com/embed/XScY1PQQku8"
		},
		{
			firstName: "DUNJA",
			familyName: "BAHTIJAREVIĆ",
			photoPath: "images/dunja bahtijarevic.jpg",
			country: "Croatia",
			countryCode: "HR",
			mainInstrument: "voix",
			otherInstruments: "",
			instrumentText: "Ce que j'aime dans la voix, c'est qu'elle s'exprime autant par la musique que par les mots. On ne se contente pas d'exprimer ce qu'on a dans la tête à travers une mélodie, comme avec les autres instruments, il faut le dire. On ne peut pas se cacher ! On pourrait dire que le chant, c'est la parole enrichie de la mélodie. La manière de parler la plus claire dans en quelque sorte.",
			presentationText: "Je suis née en Bosnie et je vis en Croatie. Je me sens chez moi dans tous les Balkans occidentaux, mais il m'arrive aussi de me sentir chez moi dans d'autres endroits. Je pense que la nostalgie m'a amené à la musique traditionnelle, et c'est à ce moment-là que j'ai commencé à me produire. J'ai commencé très tôt à faire de la musique, mais j'ai ensuite fait une grande pause en faisant d'autres choses, et maintenant, tout se mélange avec bonheur.",
			linkDescription: "Chant electronique - Kamen Gori",
			linkURL: "https://www.youtube.com/embed/FStyFhdCqKg"
		},
		{
			firstName: "ESTHER",
			familyName: "VAN KEIRSBILCK ",
			photoPath: "images/esther van keirsbilck.jpg",
			country: "Belgium",
			countryCode: "BE",
			mainInstrument: "violon, saxophone",
			otherInstruments: "saxophone alto",
			instrumentText: "Parfois, les échanges entre mon violon et d'autres instruments me touchent plus que ce qu'on aurait pu échanger avec des mots.",
			presentationText: "Je suis Bruxelloise, donc citadine, j'aime l'agitation, remplir mes journées à ras bord et faire la fête jusqu'au bout de la nuit ! La musique fait partie intégrante de ma vie, elle me fait vibrer !",
			linkDescription: "La Candèla · Brotto-Lopez",
			linkURL: "https://www.youtube.com/embed/weNVc1G8cYY"
		},
		{
			firstName: "JOANA",
			familyName: "COSTA",
			photoPath: "images/joana costa.jpg",
			country: "Portugal",
			countryCode: "PT",
			mainInstrument: "voix",
			otherInstruments: "guitare, ukulélé",
			instrumentText: "Lorsque je chante, j'ai l'impression de me connecter à une partie plus profonde de moi-même et cela me rapproche de nos sentiments. La plupart du temps, c'est la seule méthode que j'ai trouvé pour me sentir libre de les exprimer complètement.",
			presentationText: "J'ai commencé à chanter quand j'étais jeune en écoutant ma grand-mère. J'ai étudié le chant et j'aime tout ce qui est lié à la voix et comment on peut se connecter avec les autres à travers elle. ",
			linkDescription: "SOPA DE PEDRA - Ó minha amora madura",
			linkURL: "https://www.youtube.com/embed/G3AHpYp6IMg"
		},
		{
			firstName: "JUAN",
			familyName: "DE LA FUENTE",
			photoPath: "images/juan dafonte.jpg",
			country: "Portugal",
			countryCode: "PT",
			mainInstrument: "percussions",
			otherInstruments: "guitare ",
			instrumentText: "Coiffeuse en fourrure.",
			presentationText: "Je n'ai pas peur de procrastiner ou d'être triste.",
			linkDescription: "Juan Dafonte - Various percussion ensembles.",
			linkURL: "https://www.youtube.com/embed/2775E4F7Cl8"
		},
		{
			firstName: "JULIETTE",
			familyName: "MERCIER",
			photoPath: "images/juliette mercier.jpg",
			country: "France",
			countryCode: "FR",
			mainInstrument: "saxophones soprano et ténor",
			otherInstruments: "piano, voix",
			instrumentText: "Je joue du saxophone ténor et soprano. Ils ont un son chaud et expressif qui te fait voyager à travers les frontières et les époques ! Mon soprano a déjà voyagé sur le porte bagage de mon vélo !",
			presentationText: "J'ai grandi en France, aujourd'hui je vis dans la Drôme. La musique est présente dans ma vie depuis toujours, c’est un ancrage et une source de joie qui s’harmonise subtilement avec ma vie de médecin!",
			linkDescription: "Vincent Peirani & Emile Parisien - The Crave",
			linkURL: "https://www.youtube.com/embed/0DedcRgaoTs"
		},
		{
			firstName: "KATE",
			familyName: "SLIŠĀNE",
			photoPath: "images/kate slisane.jpg",
			country: "Latvia",
			countryCode: "LV",
			mainInstrument: "clarinettes, flûtes à bec, cornemuse et voix",
			otherInstruments: "mandoline, accordéon, percussions",
			instrumentText: "J'ai choisi de jouer de la clarinette à l'école primaire, sans même savoir comment cet instrument sonnait. Je l'ai choisi seulement parce qu'il commence par le même son que mon prénom. Mais maintenant, la clarinette est ma deuxième voix.",
			presentationText: "Je viens de la région la plus hospitalière et bienveillante de Lettonie - le Nord Latgale. Notre plus grande tradition musicale chantée est le pusbolss, que je vais vous faire découvrir.",
			linkDescription: "Jewish klezmer band - Freylakh Medley",
			linkURL: "https://www.youtube.com/embed/vdSQBLSLRHg"
		},
		{
			firstName: "LEA",
			familyName: "PEUVION",
			photoPath: "images/lea peuvion.jpg",
			country: "France",
			countryCode: "FR",
			mainInstrument: "violoncelle",
			otherInstruments: "violon alto, guitare",
			instrumentText: "Grondement sombre, cri déchirant, douce mélodie, rythme entrainant, de l'archet ou des doigts sur les cordes jaillissent des émotions au naturel, c'est le violoncelle ! ",
			presentationText: "Je viens d'un univers musical classique, et c'est au gré des rencontres et voyages que j'ai commencé à comprendre la magie de l'échange des musiques vivantes, depuis c'est au coeur de ma vie ! ",
			linkDescription: "SAODAJ - Monmon Kolonel",
			linkURL: "https://www.youtube.com/embed/sK_xRQ-n5UU"
		},
		{
			firstName: "MAGDALENA",
			familyName: "PACHECO",
			photoPath: "images/magdalena pacheco.jpg",
			country: "Chile",
			countryCode: "CL",
			mainInstrument: "percussions",
			otherInstruments: "",
			instrumentText: "Le rythme et la percussion sont partout. Depuis les battements de notre cœur, nos pas, nos routines jusqu'à notre horloge qui nous presse d'être à l'heure. Toutes les cultures possèdent des instruments de percussion qui accompagnent les rituels et les chants depuis les temps anciens, créant ainsi une relation entre le son des tambours et la nature, à la recherche de l'essence humaine. La percussion est le compagnon musical qui vous aide toujours à garder le rythme et vous soutient toujours dans ce que vous voulez dire. ",
			presentationText: "Je suis né et j'ai vécu toute ma vie à Santiago du Chili, à l'extrémité sud de l'Amérique du Sud, dans le pays qui ressemble à un piment. J'ai commencé à jouer des percussions à l'âge de 8 ans et c'est à ce moment-là que j'ai découvert que les percussions seraient toujours mon partenaire. J'ai commencé à jouer de la musique latino-américaine, mais j'ai vite été fasciné par la musique celtique, puis j'ai étendu mon intérêt à la musique de différentes cultures du monde, et c'est ainsi que j'ai commencé à connaître l'incroyable variété d'instruments de percussion que possède chaque culture, avec ses propres techniques et son incroyable variété de styles et de rythmes. Il existe une infinité d'instruments de percussion dans le monde, je ne perdrai donc jamais mon étonnement et mon désir d'apprendre de nouveaux instruments.",
			linkDescription: "FATIH ENSAMBLE - MIRA BIEN",
			linkURL: "https://www.youtube.com/embed/yyZDfpXDiOg"
		},
		{
			firstName: "MALENA",
			familyName: "RAMPI",
			photoPath: "images/malena rampi.jpg",
			country: "Argentina",
			countryCode: "AR",
			mainInstrument: "guitare et voix",
			otherInstruments: "piano",
			instrumentText: "L'un de mes instruments vient directement de mon corps, l'autre était autrefois un arbre et vient directement de la terre. Quand je joues des deux instruments ensemble, je sens mes pieds sur le sol.",
			presentationText: "Je suis originaire de Buenos Aires, en Argentine. J'ai grandi en écoutant beaucoup de musique, notamment les Beatles. Mes goûts musicaux vont du folklore argentin et de la musique brésilienne à la pop électronique, un mélange de musique.",
			linkDescription: "Mercedes Sosa y Luis Amaya - Zamba del chaguanco",
			linkURL: "https://www.youtube.com/embed/tWLH4vI9zXc"
		},
		{
			firstName: "MARCEL",
			familyName: "TEPPICH",
			photoPath: "images/marcel teppich.jpg",
			country: "Germany",
			countryCode: "DE",
			mainInstrument: "melodica, ukulele et harmonica",
			otherInstruments: "voix",
			instrumentText: "Mon trio personnel ? Melodica, ukulele et harmonica. Ensemble, ils sont flexibles, surprenants et déchirants, comme une belle journée d'automne.",
			presentationText: "Salut, je m'appelle Marcel et je viens d'Allemagne. Quand j'avais 17 ans, la musique s'est lentement introduite dans ma vie. Et aujourd'hui, elle est devenue une partie importante de ma vie. C'est un beau voyage sans fin ;-)",
			linkDescription: "Irish Folk - Down by the Salley Gardens",
			linkURL: "https://www.youtube.com/embed/-2WGm7Mt01c"
		},
		{
			firstName: "MATHILDE",
			familyName: "ERMAKOFF",
			photoPath: "images/mathilde ermakoff.jpg",
			country: "France",
			countryCode: "FR",
			mainInstrument: "violon",
			otherInstruments: "",
			instrumentText: "Le violon est souvent considéré comme un instrument ingrat, mais il peut être apprivoisé : on peut le faire grincer et couiner, mais également chanter et s'envoler.",
			presentationText: "Je viens de la banlieue de Paris. Je joue de la musique depuis que je suis petite, j'adore la partager avec le plus de gens possible.",
			linkDescription: "Vitali Chaconne Plays David Oistrach",
			linkURL: "https://www.youtube.com/embed/0wIwkvntrIA"
		},
		{
			firstName: "MOHAMED ",
			familyName: "BEN AOUICHA ",
			photoPath: "images/mohamed ben aouicha.jpg",
			country: "Tunisia",
			countryCode: "TN",
			mainInstrument: "percussions (riq, bandir, tbal), voix",
			otherInstruments: "oud et percussions (conga, bongos, darbouka)",
			instrumentText: "Les rythmes folkloriques tunisiens sont souvent composés sur mesure pour les chansons, en 12/8, en 6/8 ... Ces polyrythmies permettent à tous les autres instruments de s'exprimer.",
			presentationText: "Je suis originare de Kerkennah, cette île tunisienne au patrimoine musical très riche rythmiquement. J'aime cet patrimoine depuis que je suis tout petit. Je viens aussi d'une famille musiciens qui me pousse à étudier la musique.",
			linkDescription: "Un extrait du spectacle FALLEGA Nasreddine Chebli",
			linkURL: "https://www.youtube.com/embed/IJws07Fk1IQ"
		},
		{
			firstName: "NAZARÉ",
			familyName: "PINTO LEITE",
			photoPath: "images/nazare pinto leite.jpg",
			country: "Portugal",
			countryCode: "PT",
			mainInstrument: "hautbois",
			otherInstruments: "",
			instrumentText: "Le hautbois, avec son anche double, a un son très unique. Il peut être incroyablement mélancolique mais aussi puissant.",
			presentationText: "Je suis originaire du Portugal et je joue du hautbois d'aussi loin que je me souviennes. Au début, seulement de la musique classique, mais aujourd'hui, je me suis découvert une grande passion pour la musique traditionnelle/folk, surtout celle du Cap-Vert.",
			linkDescription: "",
			linkURL: "https://drive.google.com/file/d/1mUnWz3ZmhTNYSqIwgB-pOr35KpCrp0Cc/view?usp=sharing"
		},
		{
			firstName: "RAPHAËL",
			familyName: "HARDY",
			photoPath: "images/raphael hardy.jpg",
			country: "France",
			countryCode: "FR",
			mainInstrument: "guitare basse",
			otherInstruments: "",
			instrumentText: "Avec la basse électrique, même sans ampli on peut sentir les vibrations des cordes graves dans le corps. Chaque note oscille à sa manière et j'ai même lu quelque part que cela aidait à digérer. J'ai quand même un doute à ce sujet, mais j'aime bien cette sensation.",
			presentationText: "Je viens de banlieue parisienne et je fais de la musique acoustique et électronique, avec des instruments comme la basse, le piano, la guitare, le kaval, l'ordinateur et ses bizarreries.",
			linkDescription: "Orenda voices - Ja si jasem",
			linkURL: "https://www.youtube.com/embed/q_jM8XmvF90"
		},
		{
			firstName: "SEBASTIAN ",
			familyName: "PINTO ROJAS",
			photoPath: "images/sebastian pinto.jpg",
			country: "Chile",
			countryCode: "CL",
			mainInstrument: "cajón, percussions, charango",
			otherInstruments: "pandeiro, guitare, basse, voix",
			instrumentText: "Le cajon est bien plus qu'une simple boîte en bois. C'est l'un des instruments les plus polyvalents qui existent. Il est très simple à jouer et en même temps très complexe et profond. ",
			presentationText: "Je suis percussionniste et professeur de musique. Né au Chili et je vis aujourd'hui à Berlin. J'ai un lien très fort avec le Chili et la musique traditonnelle latino-américaine, mais j'adore apprendre la musique du monde entier !",
			linkDescription: "Susana Baca - Negra Presuntuosa",
			linkURL: "https://www.youtube.com/embed/ixJjpdti9jY"
		},
		{
			firstName: "SHARAD",
			familyName: "JOSHI",
			photoPath: "images/sharad joshi.jpg",
			country: "India",
			countryCode: "IN",
			mainInstrument: "voix",
			otherInstruments: "piano et percussions",
			instrumentText: "Je reviens toujours à cette citation, que reprenait aussi mon professeur : \"Chanter n'est rien d'autre que parler en accord\". C'est plus simple pour moi, je m'exprime mieux en chantant. ",
			presentationText: "La musique classique hindoustani a façonné ma vie. Avec l'expérience, j'ai appris à combiner différentes formes de musique, ce qui m'a aidé à devenir un meilleur musicien et un meilleur être humain. ",
			linkDescription: "Venkatesh Kumar - Raag Vrindavani Sarang",
			linkURL: "https://www.youtube.com/embed/EiV4GQFAtKY"
		},
		{
			firstName: "SOFÍA ",
			familyName: "GUZMÁN",
			photoPath: "images/sofia jose guzman.jpg",
			country: "Chile",
			countryCode: "CL",
			mainInstrument: "hautbois",
			otherInstruments: "guitar, pandero chilien, oeufs/shakers",
			instrumentText: "Bien que le hautbois ne soit pas un instrument populaire au Chili, c'est le vent, l'air que l'on souffle entre les anches, qui a toujours inspiré les sons des Andes.",
			presentationText: "La moitié de ma famille est péruvienne et l'autre chilienne, je trouve que le mélange est beau et la musique encore plus. J'ai un chat, et j'aime le vin et le fromage. C'est juste pour manger et boire que je viens à Ethno France ;)",
			linkDescription: "Ensamble Serenata - Temporada de Música Popular Sonidos del Mundo 2013",
			linkURL: "https://www.youtube.com/embed/GOG5Y-hT9t8"
		},
		{
			firstName: "TIAGO",
			familyName: "CANDAL",
			photoPath: "images/tiago candal.jpg",
			country: "Portugal",
			countryCode: "PT",
			mainInstrument: "accordéon, adufe et voix",
			otherInstruments: "piano, timbalão, ordinateur",
			instrumentText: "La simplicité de l'air sûr souffle fait grandir l'espace dans la poitrine.",
			presentationText: "Dans un mélange quelque peu délicat, je suis né d'une mère portugaise et d'un père brésilien. J'ai grandi dans la culture portugaise et les oreilles \"collées\" à la musique brésilienne. ",
			linkDescription: "\"Niwashi no yume\", le rêve du jardinier / Rhizottome",
			linkURL: "https://www.youtube.com/embed/gznX54EpYDo"
		}
	]
}